media:
  input: public
  output: /

content:
  - name: posts
    label: Gönderiler
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

  - name: pages
    label: Sayfalar
    path: src/pages
    type: collection
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }


  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }

      
  - name: contact
    label: İletişim Sayfası
    type: file
    path: src/pages/contact.md
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
