title: Sxinar
description: Ben Sxinar! Aktif olarak hobi şeklinde yazılım ile uğraşıyorum
  Burada yazılarımı paylaşacağım Takip etmek isterseniz blogum RSS destekler.
url: https://sxinar.github.io
cover: /assets/130384567.png
